services:

  server:
    build: .
    image: reminstant:office-reservation-server
    container_name: office-reservation-server
    environment:
      SPRING_PROFILES_ACTIVE: "container"
    ports:
      - '48080:8080'

  postgres:
    image: postgres:latest
    container_name: office-reservation-postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    volumes:
      - container_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: office-reservation-redis
    volumes:
      - container_redis_data:/data

  mongo:
    image: mongo:latest
    container_name: office-reservation-mongo
    volumes:
      - container_mongo_data:/data

volumes:
  container_pg_data:
  container_redis_data:
  container_mongo_data:
