spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/app_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      host: mongo
      port: 27017
  docker:
    compose:
      file: 'docker-compose.yaml'