spring:
  datasource:
    url: jdbc:postgresql://localhost:48081/app_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 48082
    mongodb:
      host: localhost
      port: 48083
  docker:
    compose:
      file: 'docker-compose-ide.yaml'
server:
  port: 48080
